server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TraceHub?characterEncoding=UTF-8
    username: tber
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update